# Generated by Django 6.0.7 on 2026-07-14 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 14, 10, 11, 54, 167917, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
