# Generated by Django 6.0.7 on 2026-07-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_task_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tag_task", to="catalog.tag"
            ),
        ),
    ]
